# Generated by Django 4.2.3 on 2023-11-04 09:27

from django.db import migrations, models
import policies_app.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('policy_file', models.FileField(blank=True, null=True, upload_to=policies_app.models.policy_upload_path)),
                ('policy_type', models.CharField(max_length=50, null=True)),
                ('policy_name', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'policy_master',
            },
        ),
    ]
