# Generated by Django 4.2.3 on 2023-11-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadBudget',
            new_name='UploadPolicy',
        ),
    ]
