# Generated by Django 4.2.3 on 2023-07-29 09:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('budget_no', models.CharField(max_length=50, null=True)),
                ('purpose_code', models.CharField(max_length=50, null=True)),
                ('purpose_description', models.CharField(max_length=50, null=True)),
                ('line_no', models.IntegerField(null=True)),
                ('plant', models.CharField(max_length=50, null=True)),
                ('dept', models.CharField(max_length=50, null=True)),
                ('capex_group', models.CharField(max_length=50, null=True)),
                ('capex_class', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('asset_description', models.CharField(max_length=50, null=True)),
                ('details', models.CharField(max_length=50, null=True)),
                ('rate', models.IntegerField(null=True)),
                ('qty', models.IntegerField(null=True)),
                ('uom', models.CharField(max_length=50, null=True)),
                ('final_budget', models.IntegerField(null=True)),
                ('remarks', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'capex_excel_master',
            },
        ),
        migrations.CreateModel(
            name='Capex1',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('capex_id', models.UUIDField()),
                ('nature_of_requirement', models.CharField(max_length=50, null=True)),
                ('purpose', models.CharField(max_length=50, null=True)),
                ('payback_period', models.CharField(max_length=50, null=True)),
                ('return_on_investment', models.CharField(max_length=50, null=True)),
                ('budget_type', models.CharField(max_length=50, null=True)),
                ('requisition_date', models.DateField()),
                ('total_cost', models.IntegerField(null=True)),
                ('comment1', models.CharField(max_length=100, null=True)),
                ('comment2', models.CharField(max_length=100, null=True)),
                ('comment3', models.CharField(max_length=100, null=True)),
                ('comment4', models.CharField(max_length=100, null=True)),
                ('comment5', models.CharField(max_length=100, null=True)),
                ('comment6', models.CharField(max_length=100, null=True)),
                ('comment7', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'capex_data_master',
            },
        ),
    ]
