# Generated by Django 4.2.3 on 2023-07-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capex_app', '0002_capex_created_at_capex_updated_at_capex1_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capex1',
            name='installation_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='capex1',
            name='site_delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='capex1',
            name='requisition_date',
            field=models.DateField(null=True),
        ),
    ]
