# Generated by Django 4.2.3 on 2023-07-29 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capex_app', '0003_capex1_installation_date_capex1_site_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capex1',
            name='site_delivery_date',
        ),
    ]
