# Generated by Django 4.2.3 on 2023-07-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capex_app', '0005_capex1_site_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='capex1',
            name='attachment_file_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='capex1',
            name='attachment_loc_path_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
