# Generated by Django 4.2.3 on 2023-07-31 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capex_app', '0006_capex1_attachment_file_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capex1',
            name='capex_id',
        ),
    ]
