# Generated by Django 4.2.3 on 2023-10-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capex_app', '0007_remove_capex1_capex_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capex1',
            name='attachment_file_name',
        ),
        migrations.RemoveField(
            model_name='capex1',
            name='attachment_loc_path_name',
        ),
    ]
