# Generated by Django 4.2.3 on 2023-10-10 14:51

import capex_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capex_app', '0008_remove_capex1_attachment_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capex1',
            name='user_file',
            field=models.FileField(blank=True, null=True, upload_to=capex_app.models.upload_path),
        ),
    ]
