# Generated by Django 4.2.3 on 2023-10-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capex_app', '0009_capex1_user_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='capex1',
            name='asset_list',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
