# Generated by Django 4.2.3 on 2023-10-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capex_app', '0010_capex1_asset_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='capex1',
            name='budget_id',
            field=models.UUIDField(null=True),
        ),
    ]
