# Generated by Django 4.2.3 on 2023-10-10 17:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capex_app', '0011_capex1_budget_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capex1',
            name='asset_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
