# Generated by Django 4.2.3 on 2023-10-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capex_app', '0020_remove_capex1_asset_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capex1',
            name='budget_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
