# Generated by Django 4.2.3 on 2023-10-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capex_app', '0021_alter_capex1_budget_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='capex1',
            name='asset_list',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
