# Generated by Django 4.2.3 on 2023-10-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capex_app', '0024_capex1_asset_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capex1',
            name='asset_listings',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
