# Generated by Django 4.2.3 on 2023-10-11 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capex_app', '0025_alter_capex1_asset_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capex1',
            name='asset_listings',
        ),
    ]
