# Generated by Django 4.2.3 on 2023-10-11 05:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capex_app', '0026_remove_capex1_asset_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='capex1',
            name='approvals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), default=list, size=None),
        ),
    ]
