# Generated by Django 4.2.3 on 2023-10-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capex_app', '0027_capex1_approvals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capex1',
            name='approvals',
        ),
        migrations.AddField(
            model_name='capex1',
            name='asset_listings',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
