# Generated by Django 4.2.3 on 2023-10-11 05:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('capex_app', '0028_remove_capex1_approvals_capex1_asset_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capex1',
            name='budget_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
