# Generated by Django 4.2.3 on 2023-10-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capex_app', '0030_capex1_approval_flow_capex1_capex_current_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capex1',
            name='budget_id',
            field=models.UUIDField(),
        ),
    ]
