# Generated by Django 4.2.3 on 2023-11-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capex_app', '0031_alter_capex1_budget_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='capex1',
            name='capex_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
