# Generated by Django 4.2.3 on 2023-11-01 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capex_app', '0033_capex1_flow_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capex1',
            old_name='id',
            new_name='capex_id',
        ),
    ]
