# Generated by Django 4.2.3 on 2023-11-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capex_app', '0035_rename_capex_id_capex1_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='capex1',
            name='capex_raised_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
