# Generated by Django 4.2.3 on 2023-11-02 17:30

import capex_app.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('capex_app', '0036_capex1_capex_raised_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('budget_file', models.FileField(blank=True, null=True, upload_to=capex_app.models.budget_upload_path)),
            ],
            options={
                'db_table': 'upload_budget',
            },
        ),
    ]
