# Generated by Django 4.2.3 on 2023-11-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capex_app', '0038_uploadbudget_created_at_uploadbudget_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='capex',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='capex1',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
    ]
