# Generated by Django 4.2.3 on 2023-11-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capex_app', '0039_capex_delete_flag_capex1_delete_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='capex',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
