# Generated by Django 4.2.3 on 2023-08-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorsmanagement',
            name='v_meal',
        ),
    ]
