# Generated by Django 4.2.3 on 2023-09-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0002_remove_visitorsmanagement_v_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorsmanagement',
            name='visitors',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
