# Generated by Django 4.2.3 on 2023-09-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0003_visitorsmanagement_visitors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitorsmanagement',
            old_name='appt_end_datetime',
            new_name='end_date_time',
        ),
        migrations.RenameField(
            model_name='visitorsmanagement',
            old_name='appt_start_datetime',
            new_name='start_date_time',
        ),
    ]
