# Generated by Django 4.2.3 on 2023-09-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0004_rename_appt_end_datetime_visitorsmanagement_end_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorsmanagement',
            name='v_company',
        ),
        migrations.RemoveField(
            model_name='visitorsmanagement',
            name='v_desig',
        ),
        migrations.RemoveField(
            model_name='visitorsmanagement',
            name='v_mobile_no',
        ),
        migrations.RemoveField(
            model_name='visitorsmanagement',
            name='v_name',
        ),
    ]
