# Generated by Django 4.2.3 on 2023-09-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0005_remove_visitorsmanagement_v_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorsmanagement',
            name='v_asset',
        ),
    ]
