# Generated by Django 4.2.3 on 2023-09-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0006_remove_visitorsmanagement_v_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorsmanagement',
            name='v_company',
            field=models.CharField(null=True),
        ),
    ]
