# Generated by Django 4.2.3 on 2023-09-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0007_visitorsmanagement_v_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorsmanagement',
            name='raised_by',
            field=models.CharField(null=True),
        ),
    ]
