# Generated by Django 4.2.3 on 2023-11-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0010_visitorphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorphoto',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
