# Generated by Django 4.2.3 on 2023-11-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0011_visitorphoto_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorsmanagement',
            name='punch_in_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='visitorsmanagement',
            name='punch_out_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
