# Generated by Django 4.2.3 on 2023-11-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0012_visitorsmanagement_punch_in_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorsmanagement',
            name='visitor_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
