# Generated by Django 4.2.3 on 2023-08-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanvad_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanagement',
            name='manager_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='manager',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
