# Generated by Django 4.2.3 on 2023-08-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanvad_app', '0002_usermanagement_manager_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanagement',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='usermanagement',
            name='job_type',
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='job_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
