# Generated by Django 4.2.3 on 2023-07-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sanvad_app",
            "0003_usermanagement_ed_date_usermanagement_emerg_contact_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermanagement",
            name="emerg_contact",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="usermanagement",
            name="ph_no",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
