# Generated by Django 4.2.3 on 2023-08-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanvad_app', '0003_remove_usermanagement_employment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanagement',
            name='cost_center_desc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='cost_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
