# Generated by Django 4.2.3 on 2023-08-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanvad_app', '0004_usermanagement_cost_center_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagement',
            name='emp_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
