# Generated by Django 4.2.3 on 2023-07-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sanvad_app", "0004_alter_usermanagement_emerg_contact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermanagement",
            name="module_permission_composite",
            field=models.CharField(null=True),
        ),
    ]
