# Generated by Django 4.2.3 on 2023-07-08 15:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sanvad_app", "0005_usermanagement_module_permission_composite"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermanagement",
            name="moretags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=15),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="usermanagement",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=15),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
