# Generated by Django 4.2.3 on 2023-08-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanvad_app', '0005_alter_usermanagement_emp_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagement',
            name='department',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='gender',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='manager_code',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='organization',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='plant_name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='user_role',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
