# Generated by Django 4.2.3 on 2023-07-08 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sanvad_app", "0006_usermanagement_moretags_usermanagement_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usermanagement",
            old_name="moretags",
            new_name="module_permission",
        ),
        migrations.RemoveField(
            model_name="usermanagement",
            name="module_permission_composite",
        ),
        migrations.RemoveField(
            model_name="usermanagement",
            name="tags",
        ),
    ]
