# Generated by Django 4.2.3 on 2023-07-08 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "sanvad_app",
            "0007_rename_moretags_usermanagement_module_permission_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="usermanagement",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usermanagement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
