# Generated by Django 4.2.3 on 2023-09-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanvad_app', '0007_alter_usermanagement_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagement',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
