# Generated by Django 4.2.3 on 2023-09-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanvad_app', '0008_alter_usermanagement_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagement',
            name='end_date',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
