# Generated by Django 4.2.3 on 2023-07-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sanvad_app",
            "0008_usermanagement_created_at_usermanagement_updated_at",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="usermanagement",
            old_name="user_address",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="usermanagement",
            old_name="user_department",
            new_name="department",
        ),
        migrations.RenameField(
            model_name="usermanagement",
            old_name="emp_desig",
            new_name="emp_designation",
        ),
        migrations.RenameField(
            model_name="usermanagement",
            old_name="ed_date",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="usermanagement",
            old_name="st_date",
            new_name="start_date",
        ),
        migrations.RenameField(
            model_name="usermanagement",
            old_name="user_stat",
            new_name="user_status",
        ),
        migrations.AddField(
            model_name="usermanagement",
            name="organization",
            field=models.IntegerField(null=True),
        ),
    ]
