# Generated by Django 4.2.3 on 2023-07-10 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "sanvad_app",
            "0009_rename_user_address_usermanagement_address_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="usermanagement",
            old_name="u_dob",
            new_name="dob",
        ),
    ]
