# Generated by Django 4.2.3 on 2023-07-11 06:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sanvad_app", "0010_rename_u_dob_usermanagement_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermanagement",
            name="module_permission",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=15), null=True, size=None
            ),
        ),
    ]
