# Generated by Django 4.2.3 on 2023-09-01 09:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanvad_app', '0010_alter_usermanagement_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagement',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='cost_center_desc',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='cost_code',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='department',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='dob',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='email_id',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='emerg_contact',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='emp_designation',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='emp_no',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='end_date',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='first_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='gender',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='job_status',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='manager',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='manager_code',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='module_permission',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='organization',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='password',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='ph_no',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='plant_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='start_date',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='user_role',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
