# Generated by Django 4.2.3 on 2023-10-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanvad_app', '0011_alter_usermanagement_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanagement',
            name='ess_function',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='usermanagement',
            name='ess_location',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
