# Generated by Django 4.2.3 on 2023-07-11 06:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sanvad_app", "0011_alter_usermanagement_module_permission"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usermanagement",
            old_name="user_email_id",
            new_name="email_id",
        ),
    ]
