# Generated by Django 4.2.3 on 2023-07-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanvad_app', '0012_rename_user_email_id_usermanagement_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagement',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='user_status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
