# Generated by Django 4.2.3 on 2023-10-09 10:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sanvad_app', '0012_usermanagement_ess_function_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMappings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ess_function', models.CharField(max_length=150, null=True)),
                ('ess_location', models.CharField(max_length=150, null=True)),
                ('department', models.CharField(max_length=150, null=True)),
                ('plant_name', models.CharField(max_length=150, null=True)),
            ],
            options={
                'db_table': 'employee_mappings',
            },
        ),
    ]
