# Generated by Django 4.2.3 on 2023-07-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanvad_app', '0013_alter_usermanagement_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagement',
            name='user_status',
            field=models.BooleanField(default=False),
        ),
    ]
