# Generated by Django 4.2.3 on 2023-07-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanvad_app', '0014_alter_usermanagement_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagement',
            name='emp_designation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
