# Generated by Django 4.2.3 on 2023-11-24 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announsment',
            name='announsments_title',
        ),
    ]
