# Generated by Django 4.2.3 on 2023-08-16 11:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('meeting_about', models.CharField(max_length=50, null=True)),
                ('occupancy', models.CharField(max_length=50, null=True)),
                ('start_date', models.DateField(null=True)),
                ('start_time', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('end_time', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conference_booking',
            },
        ),
    ]
