# Generated by Django 4.2.3 on 2023-08-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conferencebooking',
            old_name='end_date',
            new_name='conf_end_date',
        ),
        migrations.RenameField(
            model_name='conferencebooking',
            old_name='end_time',
            new_name='conf_start_date',
        ),
        migrations.RemoveField(
            model_name='conferencebooking',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='conferencebooking',
            name='start_time',
        ),
        migrations.AddField(
            model_name='conferencebooking',
            name='conf_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='conferencebooking',
            name='conf_start_time',
            field=models.TimeField(null=True),
        ),
    ]
