# Generated by Django 4.2.3 on 2023-08-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0002_rename_end_date_conferencebooking_conf_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencebooking',
            name='delete_flag',
            field=models.CharField(default='N', max_length=1, null=True),
        ),
    ]
