# Generated by Django 4.2.3 on 2023-08-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0003_conferencebooking_delete_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencebooking',
            name='conf_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
