# Generated by Django 4.2.3 on 2023-09-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0005_conferencebooking_conf_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencebooking',
            name='occupancy',
        ),
    ]
