# Generated by Django 4.2.3 on 2023-11-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0006_remove_conferencebooking_occupancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencebooking',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
    ]
