# Generated by Django 4.2.3 on 2023-11-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0007_alter_conferencebooking_delete_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencebooking',
            name='disp_conf_end_date',
            field=models.DateField(null=True),
        ),
    ]
