# Generated by Django 4.2.3 on 2023-09-04 09:11

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TicketSystemModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("emp_no", models.CharField(max_length=150, null=True)),
                ("ticket_no", models.IntegerField()),
                ("tkt_title", models.CharField(max_length=50, null=True)),
                ("tkt_type", models.CharField(max_length=50, null=True)),
                (
                    "tkt_description",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=150),
                        null=True,
                        size=None,
                    ),
                ),
                ("tkt_requester", models.CharField(max_length=50, null=True)),
                ("tkt_date", models.CharField(max_length=50, null=True)),
                ("tkt_status", models.CharField(max_length=50, null=True)),
                ("tkt_current_at", models.CharField(max_length=50, null=True)),
                ("tkt_docs", models.CharField(max_length=50, null=True)),
            ],
            options={
                "db_table": "tkt_system",
            },
        ),
    ]
