# Generated by Django 4.2.3 on 2023-09-04 09:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsystemmodel',
            name='tkt_description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticketsystemmodel',
            name='tkt_docs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), null=True, size=None),
        ),
    ]
