# Generated by Django 4.2.3 on 2023-09-04 10:46

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0002_alter_ticketsystemmodel_tkt_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsystemmodel',
            name='Approver_1_emp_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticketsystemmodel',
            name='Approver_1_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticketsystemmodel',
            name='Approver_2_emp_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticketsystemmodel',
            name='Approver_2_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticketsystemmodel',
            name='Approver_3_emp_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ticketsystemmodel',
            name='Approver_3_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticketsystemmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketsystemmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticketsystemmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='ticketsystemmodel',
            name='ticket_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
