# Generated by Django 4.2.3 on 2023-09-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0003_ticketsystemmodel_approver_1_emp_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsystemmodel',
            name='emp_no',
        ),
        migrations.AddField(
            model_name='ticketsystemmodel',
            name='requester_emp_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
