# Generated by Django 4.2.3 on 2023-09-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0004_remove_ticketsystemmodel_emp_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketsystemmodel',
            old_name='Approver_1_emp_no',
            new_name='approver_1_emp_no',
        ),
        migrations.RenameField(
            model_name='ticketsystemmodel',
            old_name='Approver_1_status',
            new_name='approver_1_status',
        ),
        migrations.RenameField(
            model_name='ticketsystemmodel',
            old_name='Approver_2_emp_no',
            new_name='approver_2_emp_no',
        ),
        migrations.RenameField(
            model_name='ticketsystemmodel',
            old_name='Approver_2_status',
            new_name='approver_2_status',
        ),
        migrations.RenameField(
            model_name='ticketsystemmodel',
            old_name='Approver_3_emp_no',
            new_name='approver_3_emp_no',
        ),
        migrations.RenameField(
            model_name='ticketsystemmodel',
            old_name='Approver_3_status',
            new_name='approver_3_status',
        ),
    ]
