# Generated by Django 4.2.3 on 2023-09-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0005_rename_approver_1_emp_no_ticketsystemmodel_approver_1_emp_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsystemmodel',
            name='tkt_requester',
        ),
    ]
