# Generated by Django 4.2.3 on 2023-09-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0006_remove_ticketsystemmodel_tkt_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsystemmodel',
            name='req_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
