# Generated by Django 4.2.3 on 2023-09-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0007_ticketsystemmodel_req_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsystemmodel',
            name='id',
            field=models.UUIDField(null=True),
        ),
    ]
