# Generated by Django 4.2.3 on 2023-09-18 05:23

from django.db import migrations, models
import ticket_app.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0008_alter_ticketsystemmodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketFileUploadModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ticket_ref_id', models.UUIDField()),
                ('file_name', models.CharField(max_length=100, null=True)),
                ('user_file', models.FileField(blank=True, null=True, upload_to=ticket_app.models.upload_path)),
            ],
            options={
                'db_table': 'tkt_file_uploads',
            },
        ),
    ]
