# Generated by Django 4.2.3 on 2023-09-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0009_ticketfileuploadmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketfileuploadmodel',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
