# Generated by Django 4.2.3 on 2023-10-04 11:11

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0009_ticketfileuploadmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketfileuploadmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketfileuploadmodel',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketfileuploadmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticketsystemmodel',
            name='approvals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=list), default=list, size=None),
        ),
        migrations.AddField(
            model_name='ticketsystemmodel',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketsystemmodel',
            name='severity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticketfileuploadmodel',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticketsystemmodel',
            name='tkt_description',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
