# Generated by Django 4.2.3 on 2023-09-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0010_alter_ticketfileuploadmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsystemmodel',
            name='severity',
            field=models.IntegerField(default=0),
        ),
    ]
