# Generated by Django 4.2.3 on 2023-10-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0011_ticketsystemmodel_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketfileuploadmodel',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketsystemmodel',
            name='delete_flag',
            field=models.BooleanField(default=False),
        ),
    ]
