# Generated by Django 4.2.3 on 2023-10-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0013_ticketfileuploadmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsystemmodel',
            name='tkt_description',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
