# Generated by Django 4.2.3 on 2023-10-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0014_alter_ticketsystemmodel_tkt_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsystemmodel',
            name='tkt_description',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
