# Generated by Django 4.2.3 on 2023-10-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0015_alter_ticketsystemmodel_tkt_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsystemmodel',
            name='tkt_docs',
        ),
    ]
