# Generated by Django 4.2.3 on 2023-10-04 11:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0016_remove_ticketsystemmodel_tkt_docs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsystemmodel',
            name='tkt_date',
        ),
        migrations.AddField(
            model_name='ticketsystemmodel',
            name='approvals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
        ),
    ]
