# Generated by Django 4.2.3 on 2023-10-04 11:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0017_remove_ticketsystemmodel_tkt_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsystemmodel',
            name='approver_1_emp_no',
        ),
        migrations.RemoveField(
            model_name='ticketsystemmodel',
            name='approver_1_status',
        ),
        migrations.RemoveField(
            model_name='ticketsystemmodel',
            name='approver_2_emp_no',
        ),
        migrations.RemoveField(
            model_name='ticketsystemmodel',
            name='approver_2_status',
        ),
        migrations.RemoveField(
            model_name='ticketsystemmodel',
            name='approver_3_emp_no',
        ),
        migrations.RemoveField(
            model_name='ticketsystemmodel',
            name='approver_3_status',
        ),
        migrations.AlterField(
            model_name='ticketsystemmodel',
            name='approvals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(default=list), default=list, size=None),
        ),
    ]
