# Generated by Django 4.2.3 on 2023-10-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0018_remove_ticketsystemmodel_approver_1_emp_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsystemmodel',
            name='approver_1_emp_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
