# Generated by Django 4.2.3 on 2023-10-04 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0010_ticketfileuploadmodel_created_at_and_more'),
        ('ticket_app', '0019_ticketsystemmodel_approver_1_emp_no'),
    ]

    operations = [
    ]
