# Generated by Django 4.2.3 on 2023-10-04 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0020_merge_20231004_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsystemmodel',
            name='approver_1_emp_no',
        ),
    ]
