# Generated by Django 4.2.3 on 2023-10-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0021_remove_ticketsystemmodel_approver_1_emp_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsystemmodel',
            name='approvals',
            field=models.JSONField(),
        ),
    ]
