# Generated by Django 4.2.3 on 2023-10-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0022_alter_ticketsystemmodel_approvals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsystemmodel',
            name='approvals',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
