# Generated by Django 4.2.3 on 2023-10-04 16:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0025_ticketsystemmodel_approvals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsystemmodel',
            name='approvals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), null=True, size=None),
        ),
    ]
