# Generated by Django 4.2.3 on 2023-10-04 16:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0026_alter_ticketsystemmodel_approvals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsystemmodel',
            name='approvals',
        ),
        migrations.AddField(
            model_name='ticketsystemmodel',
            name='string_array_field',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
