# Generated by Django 4.2.3 on 2023-10-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0027_remove_ticketsystemmodel_approvals_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketsystemmodel',
            old_name='string_array_field',
            new_name='approvals',
        ),
    ]
