# Generated by Django 4.2.3 on 2023-10-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0030_alter_ticketsystemmodel_approvals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsystemmodel',
            name='approvals',
            field=models.JSONField(),
        ),
    ]
