# Generated by Django 4.2.3 on 2023-10-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0031_alter_ticketsystemmodel_approvals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketsystemmodel',
            name='approvals',
        ),
        migrations.AddField(
            model_name='ticketsystemmodel',
            name='approval_flow',
            field=models.JSONField(default=False),
        ),
    ]
