# Generated by Django 4.2.3 on 2023-10-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0032_remove_ticketsystemmodel_approvals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsystemmodel',
            name='approval_flow',
            field=models.JSONField(default=dict),
        ),
    ]
