# Generated by Django 4.2.3 on 2023-10-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0034_alter_ticketsystemmodel_approval_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsystemmodel',
            name='approval_flow',
            field=models.JSONField(default=list),
        ),
    ]
