# Generated by Django 4.2.3 on 2023-11-16 06:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0035_alter_ticketsystemmodel_approval_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsystemmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
