# Generated by Django 4.2.3 on 2023-11-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0036_alter_ticketsystemmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsystemmodel',
            name='tkt_status',
            field=models.CharField(default='INPROGRESS', max_length=50, null=True),
        ),
    ]
