# Generated by Django 4.2.3 on 2023-11-16 09:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0037_alter_ticketsystemmodel_tkt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketfileuploadmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
